lib/des_todo_web/router.ex
defmodule DesTodoWeb.Router do
  use DesTodoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DesTodoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DesTodoWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/todos", TodoLive.Index, :index
    live "/todos/new", TodoLive.Index, :new
    live "/todos/:id/edit", TodoLive.Index, :edit

    live "/todos/:id", TodoLive.Show, :show
    live "/todos/:id/show/edit", TodoLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", DesTodoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DesTodoWeb.Telemetry
    end
  end
end

lib/des_todo_web/live/live_helpers.ex
defmodule DesTodoWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `DesTodoWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, DesTodoWeb.TodoLive.FormComponent,
        id: @todo.id || :new,
        action: @live_action,
        todo: @todo,
        return_to: Routes.todo_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, DesTodoWeb.ModalComponent, modal_opts)
  end
end

lib/des_todo_web/live/modal_component.ex
defmodule DesTodoWeb.ModalComponent do
  use DesTodoWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/des_todo_web/live/page_live.ex
defmodule DesTodoWeb.PageLive do
  use DesTodoWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not DesTodoWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/des_todo_web/live/todo_live/form_component.ex
defmodule DesTodoWeb.TodoLive.FormComponent do
  use DesTodoWeb, :live_component

  alias DesTodo.ToDos

  @impl true
  def update(%{todo: todo} = assigns, socket) do
    changeset = ToDos.change_todo(todo)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"todo" => todo_params}, socket) do
    changeset =
      socket.assigns.todo
      |> ToDos.change_todo(todo_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"todo" => todo_params}, socket) do
    save_todo(socket, socket.assigns.action, todo_params)
  end

  defp save_todo(socket, :edit, todo_params) do
    case ToDos.update_todo(socket.assigns.todo, todo_params) do
      {:ok, _todo} ->
        {:noreply,
         socket
         |> put_flash(:info, "Todo updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_todo(socket, :new, todo_params) do
    case ToDos.create_todo(todo_params) do
      {:ok, _todo} ->
        {:noreply,
         socket
         |> put_flash(:info, "Todo created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/des_todo_web/live/todo_live/index.ex
defmodule DesTodoWeb.TodoLive.Index do
  use DesTodoWeb, :live_view

  alias DesTodo.ToDos
  alias DesTodo.ToDos.Todo

  @impl true
  @spec mount(any, any, Phoenix.LiveView.Socket.t()) :: {:ok, Phoenix.LiveView.Socket.t()}
  def mount(_params, _session, socket) do
    hide_done = true
    socket = assign(socket, :hide_done, hide_done)
    {:ok, assign(socket, :todos, fetch_todos(hide_done))}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Todo")
    |> assign(:todo, ToDos.get_todo!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Todo")
    |> assign(:todo, %Todo{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Todos")
    |> assign(:todo, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    todo = ToDos.get_todo!(id)
    {:ok, _} = ToDos.delete_todo(todo)

    {:noreply, assign(socket, :todos, fetch_todos(false))}
  end

  def handle_event("filter", %{"filter" => %{"filter" => params}}, socket) do
    hide_done = params == "true"
    socket = assign(socket, hide_done: hide_done, todos: fetch_todos(hide_done))

    {:noreply, socket}
  end

  defp fetch_todos(hide_done) do
    todos = ToDos.list_todos()
    if hide_done do
      Enum.filter(todos, &(!&1.done))
    else
      todos
    end

  end
end

lib/des_todo_web/live/todo_live/show.ex
defmodule DesTodoWeb.TodoLive.Show do
  use DesTodoWeb, :live_view

  alias DesTodo.ToDos

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:todo, ToDos.get_todo!(id))}
  end

  defp page_title(:show), do: "Show Todo"
  defp page_title(:edit), do: "Edit Todo"
end

lib/des_todo_web/live/todo_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "todo-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :date %>
  <%= datetime_select f, :date %>
  <%= error_tag f, :date %>

  <%= label f, :theme %>
  <%= text_input f, :theme %>
  <%= error_tag f, :theme %>

  <%= label f, :due %>
  <%= date_select f, :due %>
  <%= error_tag f, :due %>

  <%= label f, :done %>
  <%= checkbox f, :done %>
  <%= error_tag f, :done %>

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

lib/des_todo_web/live/todo_live/index.html.leex
<h1>Listing Todos</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, DesTodoWeb.TodoLive.FormComponent,
    id: @todo.id || :new,
    title: @page_title,
    action: @live_action,
    todo: @todo,
    return_to: Routes.todo_index_path(@socket, :index) %>
<% end %>

<form phx-change="filter">
  <div>
    <%= checkbox(:filter, :filter, value: @hide_done)  %>
    <label>nur aktuelle</label>
  </div>
</form>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Theme</th>
      <th>Due</th>
      <th>Done</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="todos">
    <%= for todo <- @todos do %>
      <tr id="todo-<%= todo.id %>">
        <td><%= todo.date %></td>
        <td><%= todo.theme %></td>
        <td><%= todo.due %></td>
        <td style="color: <%= if todo.done do 'black' else 'red' end%>;"><%= todo.done %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.todo_show_path(@socket, :show, todo) %></span>
          <span><%= live_patch "Edit", to: Routes.todo_index_path(@socket, :edit, todo) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: todo.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Todo", to: Routes.todo_index_path(@socket, :new) %></span>

lib/des_todo_web/live/todo_live/show.html.leex
<h1>Show Todo</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, DesTodoWeb.TodoLive.FormComponent,
    id: @todo.id,
    title: @page_title,
    action: @live_action,
    todo: @todo,
    return_to: Routes.todo_show_path(@socket, :show, @todo) %>
<% end %>

<ul>

  <li>
    <strong>Date:</strong>
    <%= @todo.date %>
  </li>

  <li>
    <strong>Theme:</strong>
    <%= @todo.theme %>
  </li>

  <li>
    <strong>Due:</strong>
    <%= @todo.due %>
  </li>

  <li>
    <strong>Done:</strong>
    <%= @todo.done %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.todo_show_path(@socket, :edit, @todo), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.todo_index_path(@socket, :index) %></span>